### ISSUE TITLE
INPUT NEEDED: Research "What's Cookin" logo

### ISSUE THREAD

**Issue by Speekins** [nalito223/ticket-#5]
See possible logos below. Please vote on two or three max. Thumbs up if you like it, heart if you really like it. There's also more designs—this was not that hard to do so if anyone else is feeling passionate about this we can get on a call and look through more.
[Mock Ups for logo](https://www.canva.com/design/DAFPm5FbJN0/view)

**Comment by Speekins** [comment]
@nalito223 @sam-rice @zacwalters4

**Comment by nalito223** [comment]
Awesome work! I think the option below is my vote. I like that it's black so it matches the single tone aesthetic. 
![image](https://user-images.githubusercontent.com/110144802/197049933-c80bcd8b-84b2-4986-8170-a89e4badfac2.png)

**Comment by nalito223** [comment]
@Speekins could we identify the font used in that logo? We might be able to replicated it across the page.

**Comment by sam-rice** [comment]
Nice work with all the options! The B&W logo Tim picked out works for me as well.

I was looking at top Google serif fonts the other day with the project in mind and came across [this article](https://wplook.com/serif-fonts/). I don't mind the font used in the burger logo—and do like how it's serif—but would we want to consider a "modern" serif font? The examples from the article I linked remind me of some of the fonts used in the inspiration sites.

**Comment by Speekins** [comment]
Canva has a ton of font options. I'll make a ticket for deciding on a Google font, and once we do, we can find the matching logo font in Canva (or something close).
